name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]   
    paths:
      - 'Dockerfile'
      - 'index.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t lucak123/docker_image_537022:latest .
          docker push lucak123/docker_image_537022:latest
